---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Návratovic server"
subtitle: "Přehled"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Vítej"
  icon: "fa fa-grin"
  content: "Na tomto rozcestníku se můžeš poohlédnout po našich serverových aplikacích a službách."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Router"
    icon: "fas fa-wifi"
    url: "http://172.16.1.1/"
  # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  # - name: "another page!"
  #    icon: "fas fa-file-alt"
  #    url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Rodinné aplikace"
    icon: "fas fa-home"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Domácí Netflix"
        keywords: "netflix videa filmy seriály"
        url: "http://jellyfin.box/"
      - name: "Filebrowser"
        logo: "assets/tools/filebrowser.svg"
        subtitle: "Uložiště"
        keywords: "uložiště disk soubory"
        url: "http://filebrowser.box/"
      - name: "Home assistant"
        logo: "assets/tools/homeassistant.png"
        subtitle: "Chytrá domácnost"
        keywords: "domácnost ovládání světla"
        url: "http://homeassistant.box/"
  - name: "Tobovy aplikace"
    icon: "fas fa-cloud"
    items:
      - name: "Photoprism"
        logo: "assets/tools/photoprism.svg"
        subtitle: "Galerie"
        keywords: "galerie fotky videa"
        url: "http://photoprism.box/"
      - name: "Piwigo"
        logo: "assets/tools/piwi.svg"
        subtitle: "Webové portfolio"
        keywords: "portfolio fotky videa"
        url: "http://piwigo.box/"
      - name: "Your spotify"
        logo: "assets/tools/yourspotify.svg"
        subtitle: "Spotify statistiky"
        keywords: "spotify statistiky hudba"
        url: "http://yourspotify.box/"
      - name: "Magic mirror"
        logo: "assets/tools/mirror.png"
        subtitle: "Chytré zrcadlo"
        keywords: "zrcadlo"
        url: "http://magicmirror.box/"
      - name: "Wakapi"
        logo: "assets/tools/wakapi.png"
        subtitle: "Coding statistiky"
        keywords: "coding statistiky"
        url: "http://wakapi.box/"
      - name: "Grafana"
        logo: "assets/tools/grafana.svg"
        subtitle: "Serverové statistiky"
        keywords: "grafy statistika"
        url: "http://grafana.box"
  - name: "Služby"
    icon: "fas fa-wrench"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Blokování reklam a DNS"
        keywords: "správa pi domény"
        url: "http://pihole.box/admin"
      - name: "Nginx"
        logo: "assets/tools/nginx.png"
        subtitle: "Reverzní proxy"
        keywords: "správa proxy reverzní"
        url: "http://nginx.box"
      - name: "Vaultwarden"
        logo: "assets/tools/vaultwarden.png"
        subtitle: "Správce hesel"
        keywords: "hesla správce"
        url: "https://vaultwarden.navrattobias.cz"
      - name: "Phoscon"
        logo: "assets/tools/phoscon.png"
        subtitle: "Smart home"
        keywords: "smarthome iot"
        url: "http://phoscon.box"
      - name: "Discord music bot"
        subtitle: "DJ na discordu"
        logo: "assets/tools/discordmusicbot.gif"
        keywords: "discord music bot"
        url: "http://discordmusicbot.box"
